---
title: 'Project 2: Identifying Public WiFi Scarcity'
author: 'Group 1: Xuehan Liu, Zhilin Fan, Vikas Arun, Ken Chew, Sean Reddy'
date: "February 20, 2017"
output:
  pdf_document: default
  html_notebook: default
---

```{r}

require(dismo)
require(sp)
require(geosphere)
require(ggplot2)
require(ggmap)
require(rgeos)
require(scales)
require(raster)
require(httr)
require(httpuv)
require(jsonlite)
require(base64enc)

```

```{r}


### I believe this section is now obsolete due to Vikas's code. Vikas can you please edit this to reflect your changes?
### Ideally it will merely use "source" and reference your function you created, similarly to later code blocks.

# Your credentials, from https://www.yelp.com/developers/manage_api_keys
consumerKey = "l_rSuqvu8nD49nJ7Y3uGKw"
consumerSecret = "AZA-PdWtTt2PCTK5SFp792LGHUI"
token = "	tzJ8ZyDR2jeAm4SAEMOkJJe5gFPOkwBl"
token_secret = "e89np3uLyLE5ffunidczgL_HpRY"

yelp_query <- function(path, query_args) {
  # Use OAuth to authorize your request.
  myapp <- oauth_app("YELP", key=consumerKey, secret=consumerSecret)
  sig <- sign_oauth1.0(myapp, token=token, token_secret=token_secret)

  # Build Yelp API URL.
  scheme <- "https"
  host <- "api.yelp.com"
  yelpurl <- paste0(scheme, "://", host, path)

  # Make request.
  results <- GET(yelpurl, sig, query=query_args)

  # If status is not success, print some debugging output.
  HTTP_SUCCESS <- 200
  if (results$status != HTTP_SUCCESS) {
      print(results)
  }
  return(results)
}

yelp_search <- function(term, location, limit=10) {
  # Search term and location go in the query string.
  path <- "/v2/search"
  query_args <- list(term=term, location=location, limit=limit)

  # Make request.
  results <- yelp_query(path, query_args)
  return(results)
}

yelp_business <- function(business_id) {
  # Business ID goes in the path.
  path <- paste0("/v2/business/", business_id)
  query_args <- list()

  # Make request.
  results <- yelp_query(path, query_args)
  return(results)
}

print_search_results <- function(yelp_search_result) {
  print("=== Search Results ===")
  # Load data.  Flip it around to get an easy-to-handle list.
  locationdataContent = content(yelp_search_result)
  locationdataList=jsonlite::fromJSON(toJSON(locationdataContent))

  # Print output.
  print(head(data.frame(locationdataList)))
}

print_business_results <- function(yelp_business_result) {
  print("=== Business ===")
  print(content(yelp_business_result))
}

demo <- function(searchTerm, neighborhood, borough, limit) {
  
  ### THIS ONLY RETURNS FIRST 40. We will have to implement the built in "offset" to acquire ALL results.
  
  lat <- vector()
  lon <- vector()
  businessName <- vector()
  
  # Query Yelp API, print results.
  yelp_search_result <- yelp_search(term=tolower(searchTerm), location=paste0(neighborhood, ", " , borough,", NY"), limit=limit)

  # Pick the top search result, get more info about it.
  # Find Yelp business ID, such as "giacomos-ristorante-boston".
  #business_id = content(yelp_search_result)$businesses[[39]]$id
  #yelp_business_result <- yelp_business(business_id)
  
  numResults <- length(content(yelp_search_result)$businesses)
  
  for (i in 1:numResults){
    lat[i] <- content(yelp_search_result)$businesses[[i]]$location$coordinate$latitude
    lon[i] <- content(yelp_search_result)$businesses[[i]]$location$coordinate$longitude
    businessName[i] <- content(yelp_search_result)$businesses[[i]]$name
  }

  df <- as.data.frame(cbind(lon, lat, businessName))
  colnames(df) <- c("LON", "LAT", "name")
  
  return(df)
  

}

nbh <- read.csv("../data/neighborhoods.csv", header=TRUE)

allStarbucks <- allMcDonalds <- otherWifi <- vector()

for (borough in 1:dim(nbh)[2]){
  borough_name <- colnames(nbh)[borough]
  for (neigh in 1:dim(nbh)[1]){
    
    neigh_name <- nbh[neigh, borough]
    if (neigh_name != ""){
      allStarbucks <- rbind(allStarbucks, demo("Starbucks", neigh_name, borough_name, 40))
      allMcDonalds <- rbind(allMcDonalds, demo("McDonalds", neigh_name, borough_name, 40))
      otherWifi <- rbind(otherWifi, demo("free wifi", neigh_name, borough_name, 40))
    }
    
  }
}

allStarbucks <- unique(allStarbucks)
allMcDonalds <- unique(allMcDonalds)
otherWifi <- unique(otherWifi)
allStarbucks <- allStarbucks[allStarbucks$name == "Starbucks",]
allMcDonalds <- allMcDonalds[allMcDonalds$name == "McDonald's",]
row.names(allStarbucks) <- 1:nrow(allStarbucks)
row.names(allMcDonalds) <- 1:nrow(allMcDonalds)
row.names(otherWifi) <- 1:nrow(otherWifi)

rest_pubWifi <- rbind(allStarbucks,allMcDonalds,otherWifi)
colnames(rest_pubWifi) <- c("LON", "LAT", "network")

```

 ---  Can start running code from here if we have saved Yelp and public wifi CSVs (load libraries above though). ---

```{r}

### (1) Public WiFi Data

# Load in and format Public WiFi locations
data1 <- read.csv("../data/Free_WiFi_Hotspots_09042005.csv", header=TRUE)
data2 <- read.csv("../data/LinkNYC_Locations.csv", header=TRUE)

data_c1 <- subset(data1, select=c(LON, LAT, SSID))
data_c2 <- subset(data2, select=c(Longitude, Latitude, CB.Link.ID))

colnames(data_c1) <- colnames(data_c2) <- c("LON", "LAT","network")

```

```{r}

### (2) Taxi Data

# Load in Taxi Data
url <-"https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2016-02.csv"
#data <- read.csv(url, header=TRUE, as.is=TRUE)
data<-read.csv("../data/yellow_tripdata_2016-02.csv")

# Clean up taxi data by using both pickup/dropoff, removing empty coordinates, and removing likely erroneous coordinates.
pts <- as.data.frame(cbind(data$pickup_longitude, data$pickup_latitude, data$tpep_pickup_datetime))
colnames(pts) <- c("LON", "LAT", "TIME")
pts2 <- as.data.frame(cbind(data$dropoff_longitude, data$dropoff_latitude, data$tpep_dropoff_datetime))
colnames(pts2) <- c("LON", "LAT", "TIME")
pts3 <- as.data.frame(rbind(pts,pts2))
pts3$LON <- as.numeric(as.character(pts3$LON))
pts3$LAT <- as.numeric(as.character(pts3$LAT))
pts4 <- pts3[(pts3$LAT != 0) & (pts3$LON != 0),]
pts5 <- pts4[(pts4$LAT >= 38) & (pts4$LAT <= 44) & (pts4$LON <= -72) & (pts4$LON >= -76),]

# Remove the following line to use ALL taxi data
pts6 <- pts5[1:500000,]

# Load in shapefile
nycShapeFile <- shapefile("../data/nynta_16d/nynta.shp")

# Tag lat/lon coordinates with their respective neighborhood for taxi data
source("../doc/identifyNeighborhoodsAndBoroughs.R")
taxiData <- identifyNeighborhoodsAndBoroughs(pts6, nycShapeFile)

```


```{r}

### (3) Identify centroids of shapefile regions

# Find centroids of shapefile regions and write to CSV.
source("../doc/acquireShapefileCentroids.R")
centroids <- acquireShapefileCentroids("../data/nynta_16d/nynta.shp")
write.csv(centroids, file="../output/shapefile_neighborhood_centroids.csv")
```

```{r}

### (4) Yelp Data and Aggregation

# Read in yelp data, combine with public wifi data, and then tag with respective neighborhood based on lon/lat
yelpData <- read.csv("../output/yelpdata.csv", header=TRUE)
yelpData <- subset(yelpData, select=-c(X))

wifiData <- as.data.frame(rbind(data_c1, data_c2, yelpData))
wifiData <- identifyNeighborhoodsAndBoroughs(wifiData, nycShapeFile)
```

```{r}

### (5) Heatmap Creation

# Plot heatmaps of wifi and taxi data

source("../doc/createHeatMap.R")

#devtools::install_github("dkahle/ggmap")
#devtools::install_github("hadley/ggplot2")
#install.packages("ggplot2")
#install.packages("ggmap")
library("ggmap")
library("ggplot2")

# Show WiFi Coverage Heatmap
wifiHeatMap <- createHeatMap(neighborhood ="Murray Hill-Kips Bay", "Manhattan", wifiData, "blue")
wifiHeatMap

# Show foot traffic (proxy: taxi pickups/dropoffs) heatmap
taxiHeatMap <- createHeatMap(neighborhood="Murray Hill-Kips Bay", "Manhattan", taxiData, "red")
taxiHeatMap

# Force wifi and taxi data to same column formatting
wifiData <- subset(wifiData, select=-c(network))
taxiData <- subset(taxiData, select=-c(TIME))

# Test combined map for a given neighborhood
comboMap <- createComboHeatMap("Murray Hill-Kips Bay", borough="Manhattan", wifiData, taxiData, "blue", "red")
comboMap

# Test combined map for an entire borough
comboMap2 <- createComboHeatMap("None", borough="Bronx", wifiData, taxiData, "blue", "red")
comboMap2
```
